services:
  mysql:
    image: mysql:lts
    ports:
      - "3900:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: file_uploader
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3901:80"
volumes:
  db-data: